-- ============================================================
-- SCRIPT DE CONFIGURAÇÃO DO BANCO DE DADOS
-- Sistema de Monitoramento Ambiental - Rio Tietê
-- Execute no sqlplus após conectar no Oracle XE
--
-- Comando de conexão:
-- sqlplus /nolog
-- conn system/"SUA_SENHA"@127.0.0.1:1521/xepdb1
-- ============================================================

-- TABELAS
CREATE TABLE INSPETORES (
    ID_INSPETOR  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME         VARCHAR2(100) NOT NULL,
    MATRICULA    VARCHAR2(20)  NOT NULL UNIQUE,
    REGIAO       VARCHAR2(100) NOT NULL,
    STATUS       VARCHAR2(20)  DEFAULT 'OFFLINE',
    DT_CADASTRO  DATE          DEFAULT SYSDATE
);

CREATE TABLE INDUSTRIAS (
    ID_INDUSTRIA  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME_FANTASIA VARCHAR2(150) NOT NULL,
    CNPJ          VARCHAR2(18)  NOT NULL UNIQUE,
    MUNICIPIO     VARCHAR2(100) NOT NULL,
    SEGMENTO      VARCHAR2(100)
);

CREATE TABLE RELATORIOS (
    ID_RELATORIO  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_INSPETOR   NUMBER NOT NULL REFERENCES INSPETORES(ID_INSPETOR),
    ID_INDUSTRIA  NUMBER NOT NULL REFERENCES INDUSTRIAS(ID_INDUSTRIA),
    DT_ENVIO      DATE   DEFAULT SYSDATE,
    TIPO          VARCHAR2(30) NOT NULL,
    DESCRICAO     CLOB,
    STATUS        VARCHAR2(20) DEFAULT 'RECEBIDO'
);

CREATE TABLE MEDICOES (
    ID_MEDICAO   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_RELATORIO NUMBER NOT NULL REFERENCES RELATORIOS(ID_RELATORIO),
    PARAMETRO    VARCHAR2(80)  NOT NULL,
    VALOR        NUMBER(10,4)  NOT NULL,
    UNIDADE      VARCHAR2(20),
    NIVEL_RISCO  VARCHAR2(20)  DEFAULT 'NORMAL'
);

CREATE TABLE ALERTAS (
    ID_ALERTA    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_INDUSTRIA NUMBER REFERENCES INDUSTRIAS(ID_INDUSTRIA),
    TIPO_ALERTA  VARCHAR2(30)  NOT NULL,
    MENSAGEM     VARCHAR2(500) NOT NULL,
    DT_EMISSAO   DATE          DEFAULT SYSDATE,
    DESTINO      VARCHAR2(50)  DEFAULT 'TODOS'
);

CREATE TABLE LOGS_CONEXAO (
    ID_LOG        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_INSPETOR   NUMBER REFERENCES INSPETORES(ID_INSPETOR),
    IP_ORIGEM     VARCHAR2(45) NOT NULL,
    DT_CONEXAO    DATE         DEFAULT SYSDATE,
    DT_DESCONEXAO DATE,
    ACAO          VARCHAR2(100)
);

-- DADOS DE EXEMPLO
INSERT INTO INSPETORES (NOME, MATRICULA, REGIAO, STATUS) VALUES ('Carlos Mendes', 'INS-001', 'Salesopolis', 'ONLINE');
INSERT INTO INSPETORES (NOME, MATRICULA, REGIAO, STATUS) VALUES ('Ana Paula Rocha', 'INS-002', 'Mogi das Cruzes', 'OFFLINE');
INSERT INTO INSPETORES (NOME, MATRICULA, REGIAO, STATUS) VALUES ('Roberto Silva', 'INS-003', 'Santo Andre', 'ONLINE');
INSERT INTO INSPETORES (NOME, MATRICULA, REGIAO, STATUS) VALUES ('Henry dos Santos Carrijo', 'INS-004', 'Salesopolis', 'ONLINE');

INSERT INTO INDUSTRIAS (NOME_FANTASIA, CNPJ, MUNICIPIO, SEGMENTO) VALUES ('Metalurgica Tiete S/A', '11.222.333/0001-44', 'Salesopolis', 'Siderurgia');
INSERT INTO INDUSTRIAS (NOME_FANTASIA, CNPJ, MUNICIPIO, SEGMENTO) VALUES ('Quimica Paulista Ltda', '55.666.777/0001-88', 'Mogi das Cruzes', 'Quimica');
INSERT INTO INDUSTRIAS (NOME_FANTASIA, CNPJ, MUNICIPIO, SEGMENTO) VALUES ('Papelao do ABC', '99.000.111/0001-22', 'Santo Andre', 'Papel e Celulose');

COMMIT;
